/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

/**
 *
 * @author pc
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgotPassword = new javax.swing.JLabel();
        changePassword = new javax.swing.JLabel();
        oldSecurityQuestion = new javax.swing.JLabel();
        newSecurityQuestion = new javax.swing.JLabel();
        newAnswer = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtFieldOldSecurityQuestion = new javax.swing.JTextField();
        txtNewSecurityQuestion = new javax.swing.JTextField();
        txtFieldNewAnswer = new javax.swing.JTextField();
        pwdFieldpassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(255, 0, 0));
        forgotPassword.setText("Forgot Password");
        getContentPane().add(forgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        changePassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        changePassword.setText("Change Security Question");
        getContentPane().add(changePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 263, -1, -1));

        oldSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        oldSecurityQuestion.setText("Old Security Question");
        getContentPane().add(oldSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 312, -1, -1));

        newSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newSecurityQuestion.setText("New Security Question");
        getContentPane().add(newSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 346, -1, -1));

        newAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newAnswer.setText("New Answer");
        getContentPane().add(newAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 386, -1, -1));

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        txtFieldOldSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldOldSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldOldSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 312, 275, -1));
        getContentPane().add(txtNewSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 346, 275, -1));

        txtFieldNewAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNewAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldNewAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 386, 275, -1));
        getContentPane().add(pwdFieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 420, 275, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 502, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 502, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/first page background.PNG"))); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldOldSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldOldSecurityQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldOldSecurityQuestionActionPerformed

    private void txtFieldNewAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNewAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNewAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel changePassword;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel newAnswer;
    private javax.swing.JLabel newSecurityQuestion;
    private javax.swing.JLabel oldSecurityQuestion;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pwdFieldpassword;
    private javax.swing.JTextField txtFieldNewAnswer;
    private javax.swing.JTextField txtFieldOldSecurityQuestion;
    private javax.swing.JTextField txtNewSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
